all:
	make -C cat/ wincat
	make -C grep/ s21_grep

test:
	make -C cat/ test
	make -C grep/ test

check:
	make -C cat/ check
	make -C grep/ check

leaks:
	make -C cat/ leaks
	make -C grep/ leaks

clean:
	make -C cat/ clean
	make -C grep/ clean

